[tool.poetry]
name = "send-mail"
version = "1.0.0"
description = ""
authors = ["James T <j@elk.gg>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
